### ISSUE TITLE
[Client][FEAT] 일지 작성 모달 UI

### ISSUE THREAD

**Issue by 22yuu** [codestates-seb/seb44_main_012#101]
## 📌Feature Description

> 일지 작성 모달 UI 구현입니다.
## ✨ To-do

- [x] 사진을 추가할 수 있어야 합니다. (최대 15장)
- [x] 글을 작성할 수 있어야 합니다. (최대 300자)
- [x] 일지 작성을 취소할 수 있어야 합니다.
- [x] 반응형 UI로 작성합니다.
- [ ] 일지 작성 부분을 제외한 다른 바깥 부분 클릭할 경우에도 모달 창을 닫을 수 있어야 합니다.
