### ISSUE TITLE
[Client][FEAT] 일지 작성 모달 기능

### ISSUE THREAD

**Issue by 22yuu** [codestates-seb/seb44_main_012#103]
## 📌Feature Description

> 일지 작성 모달의 기능을 구현합니다.

## ✨ To-do

- [x] 일정 상세보기 페이지에서 생성된 일정의 마커를 클릭하면 모달 형태로 일지를 작성할 수 있는 페이지를 제공합니다.
- [x] 사진을 추가할 수 있어야 합니다.
- [x] 추가된 사진들이 여러장으로 UI 공간을 침범하게 되면, 슬라이드(캐러셀) 형태로 UI를 제공한다.
- [x] 일지 작성을 취소할 수 있어야 합니다.
- [x] 일지 작성 부분을 제외한 다른 바깥 부분 클릭할 경우에도 모달 창을 닫을 수 있어야 합니다.
- [x] 작성 중인 내용이 있다면 일지 작성을 정말로 종료할 것인지 사용자에게 의도를 다시 한 번 더 물어본다. (alert)
- [x] 유효성 검사
  - [x] 사진을 최대 15장까지 추가할 수 있습니다.
  - [x] 일지의 내용은 최대 300자까지 작성할 수 있습니다. 
- [x] 서버에 전송되어 정상적으로 데이터가 저장되어야 한다.
  - [x] 사진하고 일지의 내용은 따로 전송해야 한다.
