### ISSUE TITLE
[Client][FEAT] 나의 일정 페이지

### ISSUE THREAD

**Issue by 22yuu** [codestates-seb/seb44_main_012#132]
## 📌Feature Description

> 나의 일정 UI를 구현합니다.

## ✨ To-do

- [x] 일정 대표 이미지는 해당 지역의 default 이미지로 렌더링합니다.
- [x] 여행 이름을 표시하고 수정 및 작성할 수 있는 UI를 제공합니다.
- [x] 여행 기간, 일정 수정일, 여행할 장소 수를 보여줘야 한다.
- [x] 여행일지, 일정상세보기, 일정수정, 일정공유를 할 수 있는 버튼이 제공되어야한다.
