### ISSUE TITLE
[Client][BUG] 지도 관련 페이지 이슈

### ISSUE THREAD

**Issue by 22yuu** [codestates-seb/seb44_main_012#158]
## 📌Feature Description

일정 수정 페이지 이동 링크를 달아주면서 지도 api를 사용하는 관련 페이지들에서 몇몇 버그를 발견 했네요.

1. 나의 일정 페이지에서 일정 수정 버튼 클릭 시 페이지 이동은 정상적으로 동작합니다. 하지만 이전에 검색했던 검색 마커들이 남아 있습니다.
2. 일정 저장 후 다시 나의 일정 페이지로 왔을 때 일정 카드의 여행 장소 수가 바로 변경되지 않습니다.
3. 일정 저장한 후 리다이렉트되는 페이지가 나의 일정이 아닌 마이페이지로 되어 있습니다.
4. 일정 상세보기, 일정 작성 페이지와 같은 지도를 사용하는 페이지에서 새로고침하면 에러가 발생합니다. 예를 들어 3개의 일정이 있으면, 새로고침한 1개의 일정만 오류가 발생하고 다른 일정들은 정상 동작합니다.
> description
## ✨ To-do

- [x] 나의 일정 페이지에서 일정 수정 버튼 클릭 시 페이지 이동은 정상적으로 동작합니다. 하지만 이전에 검색했던 검색 마커들이 남아 있습니다.
- [x] 일정 저장 후 다시 나의 일정 페이지로 왔을 때 일정 카드의 여행 장소 수가 바로 변경되지 않습니다.
- [x] 일정 저장한 후 리다이렉트되는 페이지가 나의 일정이 아닌 마이페이지로 되어 있습니다.
- [x] 일정 상세보기, 일정 작성 페이지와 같은 지도를 사용하는 페이지에서 새로고침하면 에러가 발생합니다. 예를 들어 3개의 일정이 있으면, 새로고침한 1개의 일정만 오류가 발생하고 다른 일정들은 정상 동작합니다. 새로고침 후 네트워크 탭을 보면 토큰이 비어있네요. 토큰 문제 같아요
