### ISSUE TITLE
[Client][FEAT] PliP 라스트 댄스

### ISSUE THREAD

**Issue by 22yuu** [codestates-seb/seb44_main_012#160]
## 📌Feature Description

> 파이탱

## ✨ To-do

공통
- [ ] 토스트 닫기 버튼 안됨
- [ ] 특정 맥에서 폰트깨짐

랜딩페이지
- [ ] 로그인 안될 경우 여행 시작하기 버튼 누르면 로그인 유도
- [ ] 랜딩 페이지 반응형

나의 일정
- [ ] 공유하기 기능
- [ ] UI 깨짐

일정상세보기 페이지
- [ ] readonly 페이지 -> 현재 일정이 수정이 됨
- [ ] 공유버튼 UI
- [ ] 호버 시 마커위에는 장소의 정보를 보여줌,
- [ ] 왼쪽 사이드에 작성된 일지보여주기
- [ ] 일지 작성 시 생기던 버그 수정하기
  - [ ] 엔터 누르면 글자 수 30자 씩 추가됨
  - [ ] 글이 길어지면 UI가 뭉개짐 이거는 flex-1 주며 ㄴ될듯?
  - [ ] 그리고 띄워쓰기 어케할 것인지

마이페이지
- [ ] 서버 연동
- [ ] ui 약간 수정 필요

나의 발자취
- [ ] 좌표 불러와서 마커 찍기

나의 일지
- [ ] 디테일 페이지 
- [ ] 썸네일 렌더링 (없는 경우 디폴트 이미지로)

카카오
- [ ] 카카오 메시지 "자동로그인" 버튼 클릭 시 url뒤에 토큰을 붙여서 리다이렉트
- [ ] 리다이렉트 시 랜더링 페이지로

- [ ] 마스터 로그인 지우기

---  우선순위 후순위 ---
- [ ] 북마크
