### ISSUE TITLE
[Server][FEAT] 전체 코드 리팩토링1

### ISSUE THREAD

**Issue by jeein2222** [codestates-seb/seb44_main_012#173]
## 📌Feature Description

> GlobalExceptionHandler 예외처리 핸들러 추가
## ✨ To-do

- [x] 리턴하는 ResponseEntity에 제네릭 타입 추가, 컨트롤러 핸들러 메서드 리턴 타입 builder로 통일
- [x] 예외처리 핸들러 추가 -> GlobalExceptionHandler
- [x] 예외처리 추가(RecordController), @Builder.Default 추가 -> KakaoTemplateObject (테스트 코드 돌리면 warning 떠서 변경)
- [x] 코드 정렬, 포트 변경
