### ISSUE TITLE
[Client][FEAT] 여행 경로, 날짜, 일정 등록 기능

### ISSUE THREAD

**Issue by 22yuu** [codestates-seb/seb44_main_012#18]
## 📌Feature Description
> 지도 맵에서 여행 일정에 따라 이동 경로를 표시하고, 날짜와 전체 일정을 등록한다.

## ✨ To-do
- [ ] 메인 페이지에서 등록 버튼을 눌러 여행 경로를 등록할 수 있다.
- [ ] 맵에서 여행지를 표시하고, 경로를 설정한다.(이동경로는 직선으로 표시한다.)
- [ ] 최종 설정한 경로는 텍스트로 저장되어야 한다. (각 관광지의 주소, 위도와 경도 좌표도 저장되어야 한다.)
  (ex. 불국사 → 첨성대 → 동궁과 월지)
- [ ] 날짜와 더불어 여행에 대한 전체 일정을 기록한다.
