### ISSUE TITLE
[Server][FEAT] 로그아웃 API

### ISSUE THREAD

**Issue by dayoungee** [codestates-seb/seb44_main_012#19]
## 📌Feature Description

> 로그인 상태에서 로그아웃이 가능해야 한다.
## ✨ To-do

- [x] 사용자가 원할 때 로그아웃을 할 수 있어야한다.
- [ ] 토큰의 유효기간을 설정해 유효기간이 지나면 자동으로 로그아웃이 되어야 한다.
- [x] API 문서화
- [x] 테스트 코드 작성
