### ISSUE TITLE
[Server][FEAT] 회원 탈퇴 API

### ISSUE THREAD

**Issue by dayoungee** [codestates-seb/seb44_main_012#22]
## 📌Feature Description

> 회원가입을 철회할 수 있어야 한다.
## ✨ To-do

- [x] 마이페이지에서 회원 탈퇴를 진행할 수 있어야 한다.
- [x] 탈퇴를 진행할 때 비밀번호를 입력해서 본인임을 인증해야 한다.
- [x] 테스트 코드 작성
- [x] API 문서화
