### ISSUE TITLE
[Client][FEAT] 전체 여행지 맵에 표시 기능

### ISSUE THREAD

**Issue by 22yuu** [codestates-seb/seb44_main_012#23]
## 📌Feature Description
> 사용자가 방문한 여행지, 가고 싶은 여행지 (여행 일정을 기록한)가 맵에 모두 표시된다.

## ✨ To-do

- [ ] 여행 일정을 등록한 모든 여행지가 맵에 표시된다.
- [ ] 방문한 여행지와 방문 예정인 여행지의 마킹 색을 다르게 구분한다.
- [ ] 이 페이지가 메인 페이지가 된다.
- [ ] 맵에서 관광지를 선택하면, 작성한 여행 일지가 보여야 한다.
