### ISSUE TITLE
[Client][FEAT] 여행 정보 입력 기능 (여행날짜, 여행지)

### ISSUE THREAD

**Issue by jhsung23** [codestates-seb/seb44_main_012#39]
## 📌Feature Description

> 여행 일정 생성을 위한 기본 여행 정보를 받는 페이지 UI 작업입니다.
## ✨ To-do

- [x]  달력 모달로 여행 시작 날짜, 종료 날짜를 선택할 수 있어야 한다.
    - 여행 날짜를 선택하면 몇박 며칠인지 계산되어 보여줘야 한다.
- [x]  여행지를 선택할 수 있어야 한다.
    - 여행지는 서울/경기도/강원도/충청북도/충청남도/경상북도/경상남도/전라북도/전라남도/제주도로 구분한다.
- [x]  계획 작성하기 버튼 이벤트
    - 버튼 클릭 시 빈 필드가 없는지 유효성 검사를 해야한다.
        - 선택되지 않은 곳이 있다면 에러메시지를 띄워야 한다.
    - 서버에 요청을 보낸다.
        - 여행 시작일, 여행 종료일, 여행지 (등….)
    - 여행 계획 페이지로 라우팅 돼야 한다.
