### ISSUE TITLE
[Client][FEAT] 여행 계획 짜기 페이지 UI

### ISSUE THREAD

**Issue by jhsung23** [codestates-seb/seb44_main_012#40]
## 📌Feature Description

> 여행 계획 작성을 위한 페이지 UI 작업입니다.
## ✨ To-do

- [x]  여행지 지역을 확대해 지도로 보여주기
- [x]  좌측 상단 검색창
- [x]  검색 결과
    - 결과 아이템
        - 장소명, 카테고리, 도로명 주소, 전화번호
    - 결과 리스트
- [x]  검색 결과 폴백
- [x]  마커
- [x]  원형 버튼
    - 관광지, 맛집, 카페, 숙소, 프로필 사진, 홈, 공유, 장소 추가 버튼
- [x]  지도 축소/확대 버튼
- [x]  인포윈도우
    - 장소명, 카테고리, 도로명 주소, 전화번호
    - 일정에 추가하기 버튼
        - 클릭 시 추가할 날짜 선택할 수 있는 작은 모달 또는 드롭다운
- [x]  일정 타임라인 사이드바
    - 여닫기 버튼
    - 일정 아코디언
        - 일정 아이템
            - 읽기 모드
            - 편집 모드
- [x]  저장하기 버튼
- [x]  저장하기 버튼 클릭 후 다이얼로그
