### ISSUE TITLE
[Client][FEAT] 여행 계획 짜기 기능

### ISSUE THREAD

**Issue by jhsung23** [codestates-seb/seb44_main_012#41]
## 📌Feature Description

> 여행 계획 작성 기능입니다.
## ✨ To-do

- [x]  페이지 진입 시 사용자가 선택한 여행지 지도에 확대해 보여줘야 한다.
- [ ]  좌측 상단에는 검색창 인풋과 [관광명소, 맛집, 카페, 숙소] 버튼이 순서대로 보여야 한다.
    - 버튼들을 클릭하면 검색창에 버튼 이름이 입력됨과 동시에 검색한 내용을 보여줘야 한다.
    (ex) 맛집 버튼 클릭 → 검색창 인풋에 맛집이 채워진다 & 검색창 하단에 맛집 검색 결과가 나타난다.
        - 검색 결과는 카카오 지도 api에 요청해 받아온다.
        - 검색 결과의 내용에는 장소명, 카테고리, 도로명 주소, 전화번호가 포함돼야 하고, 리스트 형식으로 보여줘야 한다.
        - 검색 결과가 없을 경우 검색 결과가 없다는 폴백을 보여준다.
- [ ]  좌측 하단에는 [프로필 사진, 홈, 공유, 장소 추가] 버튼이 순서대로 보여야 한다.
    - 프로필 사진 클릭 시 마이페이지로 라우팅한다.
    - 홈 클릭 시 홈으로 라우팅한다.
    - 공유 클릭 시 → ??
    - 장소 추가 클릭 시 카카오 지도에 미등록된 장소를 추가할 수 있는 모달을 띄운다.
        - 해당 장소의 이름, 주소, 해당 장소를 추가할 여행 날짜, 카테고리(옵셔널), 전화번호(옵셔널)를 입력받는다.
        - 입력이 완료되면 지도 위 해당 주소에 마커가 꽂히고 일정에 추가된다.
- [ ]  우측 상단에는 저장하기 버튼이 있어야 한다.
    - 일정 타임라인이 나타나면 그 왼쪽에 보여져야 한다. (일정 타임라인이 해당 버튼을 가리면 안 된다.)
    - 저장하기 버튼을 누르면 현재까지 작성된 일정이 서버에 전송돼야 한다.
    - 서버에 전송이 성공적으로 완료되면 저장이 완료되었습니다, 계획 계속하기/일정 목록으로 이동하기 대화상자가 보여져야 한다.
        - 일정 목록으로 이동하기를 클릭하면 마이페이지의 나의 일정으로 라우팅돼야 한다.
- [ ]  우측 하단에는 지도를 확대, 축소할 수 있는 플러스, 마이너스 버튼이 있어야 한다.
    - 일정 타임라인이 나타나면 그 왼쪽에 보여져야 한다. (일정 타임라인이 해당 버튼을 가리면 안 된다.)
- [ ]  우측에는 일정 타임라인을 볼 수 있는 사이드바가 위치해야 한다.
    - 사이드바는 보여지는 것(open)이 기본값이다.
    - 사이드바 여닫기는 사이드바 왼쪽에 달린 버튼으로 할 수 있다.
    - 사이드바의 상단에는 여행 제목, 여행 일정, 이 일정에 초대된 유저(본인 포함)의 프로필 사진이 보여져야 한다.
    - 사이드바의 하단에는 일정 편집하기 버튼과 사용자가 선택한 장소가 아코디언으로 날짜별로 보여져야 한다.
        - 일정 편집하기 버튼
            - 버튼 클릭 시 원치 않는 장소는 삭제하고 일정의 순서를 편집할 수 있는 화면으로 변경돼야 한다.
            - 일정 편집 화면이라면 해당 버튼은 ‘편집 완료하기’로 텍스트가 변경된다.
            - 편집 완료하기 버튼을 누르면 서버에 전송한다? 만다?
        - 아코디언은 열린것이 기본값이다.
        - 추가된 일정이 없는 상태라면 ‘추가된 일정이 없습니다’ 라는 폴백을 보여준다.
- [ ]  지도에서 클릭을 하면 해당 좌표의 장소에 대한 인포윈도우를 마커 위쪽에 보여준다.
    - 인포 윈도우에는 장소명, 카테고리, 도로명 주소, 전화번호와 일정에 추가하기 버튼이 보여야 한다.
    - 일정에 추가된 장소를 클릭했다면 일정에 추가하기 버튼이 나타난다.
        - 일정에 추가하기 버튼을 누르면 며칠차에 추가할 것인지 드롭다운이 나타난다.
        - 이미 추가된 경우에 대해서는 생각하지 않음. 하루에 한 곳을 여러 번 방문하게 작성할 수도 있기 때문.
