### ISSUE TITLE
[Client][FEAT] 일정상세보기 페이지

### ISSUE THREAD

**Issue by 22yuu** [codestates-seb/seb44_main_012#42]
## 📌Feature Description

> 일정상세보기 페이지입니다.

## ✨ To-do

- [x]  `수정하기` 버튼을 누르면 일정을 수정할 수 있는 `일정짜기 페이지`로 이동한다.
- [x]  사용자가 저장한 일정들을 사이드 페널로 보여줄 수 있다.
- [x]  사이드 페널은 좌우로 숨기거나 펼칠 수 있어야 한다.
- [x]  사이드 페널의 **아이템**은 아코디언 형태로 접거나 펼칠 수 있다.
- [x]  사이드 페널의 **아이템**은 사용자가 저장한 일정들을 타임라인 형태로 보여준다.
- [x]  사용자가 저장한 일정의 장소들을 마커로 렌더링할 수 있어야 한다.
- [ ]  사용자가 원한다면 카테고리(관광지, 식당, 카페, 호텔) 별로 마커들을 렌더링할 수 있어야 한다.
    
   ![image](https://github.com/codestates-seb/seb44_main_012/assets/48381447/f4c0669b-2593-4f6d-b300-28846480b21d)
    
- [ ]  마커를 호버하면 작성된 일지를 오버레이로 보여준다. 
    - 작성되어 있지 않다면 시각적인 피드백을 제공하거나 오버레이 형태로 작성되어 있지 않음을 사용자에게 알려준다.
    - 이미 작성되어 있다면 추가로 작성할 수 있어야 한다.
    - 작성된 일지가 여러개라면 가장 최신 일지를 오버레이한다.
- [x]  마커를 클릭하면 해당 장소에 대한 일지를 작성할 수 있는 모달창을 띄운다.
- [ ]  여행 일정은 다른 사람들에게 링크 형태로 공유할 수 있어야 한다.
    - 일정상세보기 페이지는 읽기 전용 페이지이다.
    - 지금은 일정을 생성한 생성자만이 일정을 수정할 수 있도록 한다.
    - 생성자 외 회원 혹은 비회원은 `수정하기` 버튼은 비활성화(disable) UI로 보여준다.
    ![image](https://github.com/codestates-seb/seb44_main_012/assets/48381447/e222c5b1-d4a3-42d4-a114-2b92e63b0cba)

    
- [x] 프로필 버튼을 클릭하면 `마이페이지` 페이지로 이동한다.
    - 비회원이라면 로그인 유도 대화상자를 띄운다. ok 누르면 로그인 페이지 렌더링 취소 시 현재 페이지에서 머무른다.
    - 회원이라면 마이페이지로 이동한다.
 ![image](https://github.com/codestates-seb/seb44_main_012/assets/48381447/1e7e1dce-ca46-4814-8ad9-579bfeea96db)
    
    
- [x] 홈 버튼을 클릭하면 메인 페이지로 이동한다.
 ![image](https://github.com/codestates-seb/seb44_main_012/assets/48381447/fa26bc48-e057-4df4-bedf-5e5239eb9c98)
