### ISSUE TITLE
[Server][FEAT] 회원 가입 API

### ISSUE THREAD

**Issue by dayoungee** [codestates-seb/seb44_main_012#5]
## 📌Feature Description

> 사용자가 직접 입력한 아이디와 비밀번호를 통해 회원 가입을 한다.
## ✨ To-do

- [x]  email과 닉네임은 중복되어선 안된다.
- [x]  비밀번호는 암호화 되어 DB에 저장되어야 한다.
- [x] 회원 가입 정보에는 email, 닉네임, 비밀번호를 입력받아야 한다.
- [x] email 검증을 위해 인증번호를 발송하고 인증번호로 자신의 email임을 인증해야 한다.
- [ ] 비밀번호를 두 번 입력 받아 비밀번호 검증 과정을 거쳐야한다.
- [x] email, 닉네임, 비밀번호는 유효성 검증을 거쳐야 한다.
  →  email 형식으로 가입해야함(0000@000.000)
  →  닉네임은 문자, 숫자로 2글자 이상 10글자 이하여야 한다.
  →  비빌번호는 8자리 이상 영문, 숫자, 특수 문자를 합쳐야 한다. 
- [x] 테스트 코드 작성
- [x] API 문서화 진행
