### ISSUE TITLE
[Client][FEAT] Header 공통 컴포넌트 구현

### ISSUE THREAD

**Issue by 22yuu** [codestates-seb/seb44_main_012#55]
## 📌Feature Description

> 헤더 공통 컴포넌트를 구현합니다.

## ✨ To-do

- [x] 로고와 사명이 들어가야 합니다.
- [x] 로그인 전 `Sigin in` `Sigin up` 버튼이 노출되어야 합니다.
- [x] 로그인 후 마이페이지 아이콘, 알림 아이콘, 프로필 사진, 닉네임, 드롭다운 메뉴 버튼이 노출되어야 합니다.
- [x] 로그아웃 버튼을 누르면 로그아웃이 되어야 합니다.
