### ISSUE TITLE
[Client][FEAT] 헤더 컴포넌트 드롭다운 메뉴 기능구현

### ISSUE THREAD

**Issue by 22yuu** [codestates-seb/seb44_main_012#78]
## 📌Feature Description

> 헤더 컴포넌트 드롭다운 메뉴 기능구현

## ✨ To-do

- [x] 헤더에서 사용자의 닉네임 혹은 `arrow` 아이콘 클릭 시 드롭다운 메뉴를 제공합니다.
- [x] 드롭다운 메뉴 아이템 클릭 시 해당하는 페이지로 이동 가능해야 합니다.
- [x] 드롭다운 메뉴는 토글이 가능해야 합니다.
- [x] 사용자가 드롭다운 메뉴 UI 외부 화면에 클릭 시 드롭다운 메뉴는 제거되어야 합니다.
